application: mol-api
version: pytaxrefine
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: .*
  script: app.app

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
